site_name: 'Cyber Notes Vault'  # Customize your site name
docs_dir: Cyber-Notes
markdown_extensions:
  - admonition  # For note blocks like warnings, tips, etc.
  - codehilite  # Syntax highlighting for code blocks
  - pymdownx.details
  - pymdownx.superfences
use_directory_urls: true
extra:
  navigation_depth: 1  # Prevent headers from being used as links
theme:
  name: material  # You can replace with another theme if preferred

